
try:
    print(x)
    
# except NameError:
#     print("Variable x is not defined")

except:
    print("an eception occurred")
    
finally:
    print("The 'try except' is finished")